team_id('123456789') # <- CHANGE

app_identifier("com.hoppsen.template")

# Source: https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/tunes/app_submission.rb
submission_information({
    add_id_info_serves_ads: false,
    add_id_info_tracks_action: false,
    add_id_info_tracks_install: false,
    add_id_info_uses_idfa: false,
    content_rights_contains_third_party_content: false,
    content_rights_has_rights: false,
    # BELOW IS NOT NEEDED. JUST LEFT IT FOR REFERENCE
    # export_compliance_available_on_french_store: false,
    # export_compliance_contains_proprietary_cryptography: false,
    # export_compliance_contains_third_party_cryptography: false,
    # export_compliance_is_exempt: false,
    # export_compliance_uses_encryption: false,
    # export_compliance_app_type: nil,
    # export_compliance_encryption_updated: false,
    # export_compliance_compliance_required: false,
    # export_compliance_platform: 'ios',
})
